# Generated by Django 6.0 on 2025-12-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=254)),
                ('phones', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=500)),
                ('times', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='i readed this message')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
