# Generated by Django 6.0 on 2025-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
